### ISSUE TITLE
Failing to get available flights

### ISSUE THREAD

**Issue by hoopsbwc34** [Fffrank/southwest-alerts#12]
I'm successfully logging into southwest with the script and getting my future flights, but in the following code, available is returning with "None" as if the URL request in get_available_flights() didn't work.  This started abruptly last week after running successfully the several times the day before.  Anyone else having this issue?  Is this request also happening "logged in" to my southwest account, or is it a completely different request of the mobile API without the headers? 

```
available = southwest.get_available_flights(
                        departure_date,
                        origin_airport,
                        destination_airport
                    )
```

**Comment by Fffrank** [comment]
I updated it a few days ago -- the request URL changed.
